[package]
name = "modulix-core-utils"
version = "0.1.0"
edition = "2024"

[features]
# Core
core-nix-file = ["dep:rnix", "dep:rowan", "unix"]
core-user-info = ["dep:serde", "serde-json"]
core-app-info-trait = [
    "dep:phf",
    "dep:serde",
]

# Modules
package-info = [
    "core-app-info-trait",
    "dep:serde",
    "serde-json",
    "dep:tokio"
]
app-info-gui = [
    "core-app-info-trait",
    "reqwest"
]
config-store = []
desktop-environment = [
    "config-store",
    "core-user-info",
    "dep:walkdir",
    "dep:glob"
]
detect-hardware = [
    "dep:regex",
    "dep:serde",
    "serde-json"
]
filesystem = ["core-nix-file"]
firewall = ["core-nix-file"]
flake-input = ["core-nix-file"]
hardware-config = [
    "detect-hardware",
    "core-nix-file"
]
init = [
    "core-nix-file",
    "filesystem"
]
locale = ["core-nix-file"]
modulix-module = ["core-nix-file"]
module-info = [
    "core-app-info-trait",
    "dep:serde",
    "serde-json",
    "dep:tokio",
    "reqwest"
]
install-module = [
    "core-nix-file",
    "module-info",
    "serde-json",
    "dep:tokio",
    "core-app-info-trait"
]
install-package = [
    "core-nix-file",
    "package-info",
    "dep:phf",
    "dep:xz2",
    "serde-json",
    "dep:tokio",
    "core-app-info-trait"
]
user = ["core-nix-file"]

# wrapped dependencies
serde-json = ["dep:serde_json"]
reqwest = ["dep:reqwest"]
unix = ["dep:nix"]


# Generator
flathub-info-gen = [
    "reqwest",
    "serde-json",
    "dep:futures",
    "dep:tokio",
    "dep:serde",
    "dep:phf",
]

[dependencies]
const_format = "0.2.36"
git2 = "0.21.0"

# Optionnal
glob = { version = "0.3.3", optional = true }
nix = { version = "0.31.3", features = ["fs", "ioctl"], optional = true }
regex = { version = "1.12.3", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
walkdir = { version = "2.5.0", optional = true }
phf = { version = "0.13.1", features = ["macros"], optional = true }
xz2 = { version = "0.1.7", optional = true }
rnix = { version = "0.14.0", optional = true }
rowan = { version = "0.16.1", optional = true }
reqwest = { version = "0.13.3", features = ["json"], optional = true }
futures = { version = "0.3.32", optional = true }
serde_json = { version = "1.0.150", optional = true }
tokio = { version = "1.52.3", features = ["macros", "process", "rt-multi-thread"], optional = true }

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "flathub-info-gen"
path = "bin/flathub-info-gen.rs"
required-features = ["flathub-info-gen"]

[[exemple]]
name = "filesystem"
required-features = ["filesystem"]

[[exemple]]
name = "search-package"
required-features = ["package-info", "app-info-gui", "dep:tokio"]

[[exemple]]
name = "package"
required-features = ["install-package"]

[[exemple]]
name = "module"
required-features = ["install-module"]

[[exemple]]
name = "search_module"
required-features = ["module-info", "app-info-gui"]

[[exemple]]
name = "firewall"
required-features = ["firewall"]

[[exemple]]
name = "flake_input"
required-features = ["flake-input"]
